# air.toml
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  follow_symlink = true
  exclude_regex = ["_test\\.go"]
  delay = 1000
  stop_on_error = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
